
package com.tilde.tagger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TaggerServiceSoap", targetNamespace = "http://www.tilde.com/tagger/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaggerServiceSoap {


    /**
     * 
     * @param text
     * @param lang
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Tokenize", action = "http://www.tilde.com/tagger/Tokenize")
    @WebResult(name = "TokenizeResult", targetNamespace = "http://www.tilde.com/tagger/")
    @RequestWrapper(localName = "Tokenize", targetNamespace = "http://www.tilde.com/tagger/", className = "com.tilde.tagger.Tokenize")
    @ResponseWrapper(localName = "TokenizeResponse", targetNamespace = "http://www.tilde.com/tagger/", className = "com.tilde.tagger.TokenizeResponse")
    public String tokenize(
        @WebParam(name = "text", targetNamespace = "http://www.tilde.com/tagger/")
        String text,
        @WebParam(name = "lang", targetNamespace = "http://www.tilde.com/tagger/")
        String lang);

    /**
     * 
     * @param text
     * @param lang
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BreakSentences", action = "http://www.tilde.com/tagger/BreakSentences")
    @WebResult(name = "BreakSentencesResult", targetNamespace = "http://www.tilde.com/tagger/")
    @RequestWrapper(localName = "BreakSentences", targetNamespace = "http://www.tilde.com/tagger/", className = "com.tilde.tagger.BreakSentences")
    @ResponseWrapper(localName = "BreakSentencesResponse", targetNamespace = "http://www.tilde.com/tagger/", className = "com.tilde.tagger.BreakSentencesResponse")
    public String breakSentences(
        @WebParam(name = "text", targetNamespace = "http://www.tilde.com/tagger/")
        String text,
        @WebParam(name = "lang", targetNamespace = "http://www.tilde.com/tagger/")
        String lang);

    /**
     * 
     * @param text
     * @param outputFormat
     * @param lang
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PosTagger", action = "http://www.tilde.com/tagger/PosTagger")
    @WebResult(name = "PosTaggerResult", targetNamespace = "http://www.tilde.com/tagger/")
    @RequestWrapper(localName = "PosTagger", targetNamespace = "http://www.tilde.com/tagger/", className = "com.tilde.tagger.PosTagger")
    @ResponseWrapper(localName = "PosTaggerResponse", targetNamespace = "http://www.tilde.com/tagger/", className = "com.tilde.tagger.PosTaggerResponse")
    public String posTagger(
        @WebParam(name = "text", targetNamespace = "http://www.tilde.com/tagger/")
        String text,
        @WebParam(name = "outputFormat", targetNamespace = "http://www.tilde.com/tagger/")
        String outputFormat,
        @WebParam(name = "lang", targetNamespace = "http://www.tilde.com/tagger/")
        String lang);

}
