
package com.tilde.tagger;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TaggerService", targetNamespace = "http://www.tilde.com/tagger/", wsdlLocation = "file:/home/rocheteau-j/Repositories/GoogleCode/ttc-project/trunk/modules/ttc-components/resources/tagger.wsdl")
public class TaggerService
    extends Service
{

    public final static URL TAGGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tilde.tagger.TaggerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tilde.tagger.TaggerService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/rocheteau-j/Repositories/GoogleCode/ttc-project/trunk/modules/ttc-components/resources/tagger.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/rocheteau-j/Repositories/GoogleCode/ttc-project/trunk/modules/ttc-components/resources/tagger.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TAGGERSERVICE_WSDL_LOCATION = url;
    }

    public TaggerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaggerService() {
        super(TAGGERSERVICE_WSDL_LOCATION, new QName("http://www.tilde.com/tagger/", "TaggerService"));
    }

    /**
     * 
     * @return
     *     returns TaggerServiceSoap
     */
    @WebEndpoint(name = "TaggerServiceSoap")
    public TaggerServiceSoap getTaggerServiceSoap() {
        return super.getPort(new QName("http://www.tilde.com/tagger/", "TaggerServiceSoap"), TaggerServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaggerServiceSoap
     */
    @WebEndpoint(name = "TaggerServiceSoap")
    public TaggerServiceSoap getTaggerServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tilde.com/tagger/", "TaggerServiceSoap"), TaggerServiceSoap.class, features);
    }

}
