//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.15 at 11:03:27 PM CET 
//


package uima.sandbox.catcher.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="variable" type="{}Variable"/>
 *         &lt;element name="integer" type="{}Integer"/>
 *         &lt;element name="string" type="{}String"/>
 *         &lt;element name="feature" type="{}Feature"/>
 *         &lt;element name="plus" type="{}Plus"/>
 *         &lt;element name="minus" type="{}Minus"/>
 *         &lt;element name="mult" type="{}Mult"/>
 *         &lt;element name="div" type="{}Div"/>
 *         &lt;element name="get" type="{}Get"/>
 *         &lt;element name="sub" type="{}Sub"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element", propOrder = {
    "variable",
    "integer",
    "string",
    "feature",
    "plus",
    "minus",
    "mult",
    "div",
    "get",
    "sub"
})
public class Element {

    protected Variable variable;
    protected Integer integer;
    protected String string;
    protected Feature feature;
    protected Plus plus;
    protected Minus minus;
    protected Mult mult;
    protected Div div;
    protected Get get;
    protected Sub sub;

    /**
     * Gets the value of the variable property.
     * 
     * @return
     *     possible object is
     *     {@link Variable }
     *     
     */
    public Variable getVariable() {
        return variable;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variable }
     *     
     */
    public void setVariable(Variable value) {
        this.variable = value;
    }

    /**
     * Gets the value of the integer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInteger() {
        return integer;
    }

    /**
     * Sets the value of the integer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInteger(Integer value) {
        this.integer = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setString(String value) {
        this.string = value;
    }

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link Feature }
     *     
     */
    public Feature getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Feature }
     *     
     */
    public void setFeature(Feature value) {
        this.feature = value;
    }

    /**
     * Gets the value of the plus property.
     * 
     * @return
     *     possible object is
     *     {@link Plus }
     *     
     */
    public Plus getPlus() {
        return plus;
    }

    /**
     * Sets the value of the plus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plus }
     *     
     */
    public void setPlus(Plus value) {
        this.plus = value;
    }

    /**
     * Gets the value of the minus property.
     * 
     * @return
     *     possible object is
     *     {@link Minus }
     *     
     */
    public Minus getMinus() {
        return minus;
    }

    /**
     * Sets the value of the minus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Minus }
     *     
     */
    public void setMinus(Minus value) {
        this.minus = value;
    }

    /**
     * Gets the value of the mult property.
     * 
     * @return
     *     possible object is
     *     {@link Mult }
     *     
     */
    public Mult getMult() {
        return mult;
    }

    /**
     * Sets the value of the mult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mult }
     *     
     */
    public void setMult(Mult value) {
        this.mult = value;
    }

    /**
     * Gets the value of the div property.
     * 
     * @return
     *     possible object is
     *     {@link Div }
     *     
     */
    public Div getDiv() {
        return div;
    }

    /**
     * Sets the value of the div property.
     * 
     * @param value
     *     allowed object is
     *     {@link Div }
     *     
     */
    public void setDiv(Div value) {
        this.div = value;
    }

    /**
     * Gets the value of the get property.
     * 
     * @return
     *     possible object is
     *     {@link Get }
     *     
     */
    public Get getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     * @param value
     *     allowed object is
     *     {@link Get }
     *     
     */
    public void setGet(Get value) {
        this.get = value;
    }

    /**
     * Gets the value of the sub property.
     * 
     * @return
     *     possible object is
     *     {@link Sub }
     *     
     */
    public Sub getSub() {
        return sub;
    }

    /**
     * Sets the value of the sub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sub }
     *     
     */
    public void setSub(Sub value) {
        this.sub = value;
    }

}
